### ISSUE TITLE
Questions about the quantity of generating data

### ISSUE THREAD

**Issue by SupritYoung** [DAMO-NLP-SG/BGCA#2]
Thanks for your outstanding Contribution ❤️, your data augmentation method is very novel! After carefully reading your papaer, there's one quesiton that would like to consult:

Is the quantity of unlabeled dats used for generation pseudo label always one-to-one ? Is it feasible that generating multiple pseudo data given one sample?

**Comment by ntudy** [comment]
Hi, thank you for your question. We have increased the generation number of pseudo labels through non-deterministic sampling. However, we found that the improvement achieved was not significant. Therefore, we have decided to assign one pseudo label to each unlabeled data point instead.

But this may vary across different models and datasets, so you may try it on your model and dataset and see the result.
