### ISSUE TITLE
Question about the formulas

### ISSUE THREAD

**Issue by namphamquang** [DAMO-NLP-SG/BGCA#3]
Thank you for the knowledge in your research article. I have read and understood the ideas of the methods. 
However, I encountered some ambiguities in some of the formulas. For example, formula 2, what is (l) (sequence of ...), why does (i) start from -1. 
It would be valuable if I received a detailed explanation for this formula, and if possible, for each of formulas 2, 3, 5, 6.
Thank you very much!

**Comment by ntudy** [comment]
Hi, thank you for pointing this out! We have a typo in formulas 2 and 5, where i should start from 1. For a better understanding of these formulas, you may refer to the following resources:

1. text generation: https://web.stanford.edu/class/archive/cs/cs224n/cs224n.1224/slides/cs224n-2022-lecture12-generation-final.pdf
2. Constrained decoding: https://aclanthology.org/P17-1141/
